drop table if exists clientes cascade;
drop table if exists personas cascade;

create table personas (
    id bigint generated by default as identity,
    direccion varchar(255),
    edad integer,
    genero varchar(255),
    identificacion varchar(255),
    nombre varchar(255),
    telefono varchar(255),
    primary key (id)
);

create table clientes (
    id bigint not null,
    cliente_id varchar(255) not null unique,
    contraseña varchar(255),
    estado boolean,
    primary key (id),
    foreign key (id) references personas(id)
);
