-- Eliminar tablas existentes si ya existen (con cascada para eliminar dependencias)
DROP TABLE IF EXISTS clientes CASCADE;
DROP TABLE IF EXISTS personas CASCADE;

-- Crear tabla personas
CREATE TABLE personas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY, -- Generación automática de ID
    direccion VARCHAR(255),
    edad INTEGER,
    genero VARCHAR(255),
    identificacion VARCHAR(255) UNIQUE, -- Indice unico
    nombre VARCHAR(255),
    telefono VARCHAR(255),
    PRIMARY KEY (id)
);

-- Crear indices para la tabla personas
CREATE INDEX idx_persona_nombre ON personas (nombre); -- Índice en 'nombre'
CREATE INDEX idx_persona_telefono ON personas (telefono); -- Índice en 'telefono'

-- Crear tabla clientes
CREATE TABLE clientes (
    id BIGINT NOT NULL,
    cliente_id VARCHAR(255) NOT NULL UNIQUE, -- Indice unico
    contrasenia VARCHAR(255),
    estado BOOLEAN,
    PRIMARY KEY (id),
    FOREIGN KEY (id) REFERENCES personas(id) -- Clave fornea hacia 'personas'
);

-- Crear índices para la tabla clientes
CREATE UNIQUE INDEX idx_cliente_cliente_id ON clientes (cliente_id); -- Índice único en 'cliente_id'
