version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672" # RabbitMQ broker
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  customers:
    build:
      context: ./customers
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq

  accounts:
    build:
      context: ./accounts
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
